### ISSUE TITLE
originMemberNode attribute is modified when only modifying the submitter attribute

### ISSUE THREAD

**Issue by servilla** [DataONEorg/d1_python#12]
The "originMemberNode" attribute is modified to the current member node identifier when only modifying the "submitter" attribute in the MemberNodeClient_2_0.updateSystemMetadata() method call in GMN v2.3.10.

**Comment by servilla** [comment]
Actually, when using MemberNodeClient_2_0.updateSystemMetadata(), both "originMemberNode" and "submitter" are altered back to the current member node identifier if not provided explicitly in the new sysmeta pyxb object provided to the updateSystemMetadata() method.

**Comment by rogerdahl** [comment]
Fixed in upcoming. In basic science object `create()` and `update()` a field that is left out in the system metadata means "fall back to MN default or leave unfilled if there is no default." `updateSystemMetadata()` was set up the same way, but that wasn't right for mandatory fields such as `originMemberNode` and `submitter`. Those will now remain at defaults when left out of the sysmeta in `updateSystemMetadata()`.

Other fields that are left out will still fall back to MN defaults or be deleted. This is so that it's possible to remove a non-mandatory system metadata value altogether with `updateSystemMetadata()`, not just replace it with another value. Since, `updateSystemMetadata()` is intended to be used in a read-modify-write cycle together with `getSystemMetadata(), this works out so that fields that are not modified by the client between the get and update calls remain unchanged.
