### ISSUE TITLE
gmn/manage.py import --no-bytes CLI parameter does not exist

### ISSUE THREAD

**Issue by servilla** [DataONEorg/d1_python#8]
As documented in the `python manage.py import --help`

```
- Start the import. Since the new instance has been set up to use the same
object storage location as the old instance, use the `--no-bytes` switch, which
tells GMN not to copy the object bytes and instead assume that they are already
available in the object storage location.

    $ manage.py import --no-bytes
```

Does not exist when executing the command.

**Comment by rogerdahl** [comment]
Sorry, outdated docs. The switch is no longer needed because the importer
automatically skips the get() call for objects where the bytes are already
present.

On Sep 26, 2017 8:53 PM, "Mark Servilla" <notifications@github.com> wrote:

As documented in the python manage.py import --help

- Start the import. Since the new instance has been set up to use the same
object storage location as the old instance, use the `--no-bytes` switch, which
tells GMN not to copy the object bytes and instead assume that they are already
available in the object storage location.

    $ manage.py import --no-bytes

Does not exist when executing the command.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DataONEorg/d1_python/issues/8>, or mute the thread

**Comment by rogerdahl** [comment]
Docs updated.
